backend:
  name: git-gateway
  repo: samhitask/yujr-website 
  branch: master 


media_folder: "public/images/uploads" # Where uploaded images are stored
public_folder: "/images/uploads" # Public URL for images

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }